/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/kick.glb')
  const { actions } = useAnimations(animations, group)
  console.log(nodes)
  console.log(nodes.mixamorigHips)
  useEffect(()=>{
    nodes.mixamorigHips.position.setScalar(0);
 
   
    actions.kick.play()
   console.log(actions)
   })
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Ch03.geometry}
          material={materials['Ch03_Body.001']}
          skeleton={nodes.Ch03.skeleton}
          
          
        />
      </group>
    </group>
  )
}

useGLTF.preload('/kick.glb')
