/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/rain_rig.glb')
  const { ref,actions, names } = useAnimations(animations, group)

  const [hovered, setHovered] = useState(false)
  const [index, setIndex] = useState(7)

  useEffect(() => void (document.body.style.cursor = hovered ? "pointer" : "auto"), [hovered])
  // Change animation when the index changes
  
  useEffect(() => {
    console.log(nodes['GEO-rain_eyelashes'])

    // Reset and fade in animation after an index has been changed
    actions[names[index]].reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
    return () => actions[names[index]].fadeOut(0.5)
  }, [index, actions, names])
  
  return (
    <group ref={group} {...props} dispose={null} scale={5}>
      <primitive object={nodes.TeethT} />
      <primitive object={nodes.TeethB} />
      <primitive object={nodes['P-BB-ChinM']} />
      <primitive object={nodes['P-GRP-Lip_TopM']} />
      <primitive object={nodes['P-BB-Chin_2L']} />
      <primitive object={nodes['P-BB-LaughLineM']} />
      <primitive object={nodes['P-BB-LaughLine_7L']} />
      <primitive object={nodes['P-GRP-Lip_BotM']} />
      <primitive object={nodes['FK-ToeL']} />
      <primitive object={nodes['DEF-COR-Shin_TopL']} />
      <primitive object={nodes['P-BB-JawLine_3L']} />
      <primitive object={nodes['P-BB-Nose_3M']} />
      <primitive object={nodes['P-BB-Cheek_SneerL']} />
      <primitive object={nodes['P-BB-Cheek_3_2L']} />
      <primitive object={nodes['P-BB-Cheek_2_2L']} />
      <primitive object={nodes['P-BB-LaughLine_2L']} />
      <primitive object={nodes['P-BB-Nostril_2L']} />
      <primitive object={nodes['P-BB-Nostril_1L']} />
      <primitive object={nodes['P-BB-LaughLine_1L']} />
      <primitive object={nodes['P-BB-LaughLine_6L']} />
      <primitive object={nodes['P-BB-LaughLine_4L']} />
      <primitive object={nodes['P-BB-Cheek_2_1L']} />
      <primitive object={nodes['P-BB-Cheek_3_1L']} />
      <primitive object={nodes['P-BB-JawLine_2L']} />
      <primitive object={nodes['P-BB-LaughLine_5L']} />
      <primitive object={nodes['P-BB-Cheek_1_2L']} />
      <primitive object={nodes['P-BB-Cheek_4_2L']} />
      <primitive object={nodes['P-BB-Cheek_1_1L']} />
      <primitive object={nodes['P-GRP-Nose_Front']} />
      <primitive object={nodes['P-GRP-Lip_Top_1L']} />
      <primitive object={nodes['P-GRP-Lip_Bot_1L']} />
      <primitive object={nodes.Tongue_Root} />
      <primitive object={nodes['N-BB-Lip_Bot_BotM']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Bot_1L']} />
      <primitive object={nodes['N-TAN-Lip_Bot_AcrossM']} />
      <primitive object={nodes['N-BB-Lip_Bot_TopM']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_AcrossM']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Top_1L']} />
      <primitive object={nodes['HNG-ThighL']} />
      <primitive object={nodes['HNG-Upperarm_ParentL']} />
      <primitive object={nodes['CTR-COR-Thumb_1L']} />
      <primitive object={nodes['P-FK-Head']} />
      <primitive object={nodes['P-GRP-Lip_Bot_2L']} />
      <primitive object={nodes['P-GRP-Lip_Bot_2R']} />
      <primitive object={nodes['P-GRP-Lip_Top_2L']} />
      <primitive object={nodes['P-GRP-Lip_Top_2R']} />
      <primitive object={nodes['P-ACT-Lips_CornerL']} />
      <primitive object={nodes['P-ACT-Lips_CornerR']} />
      <primitive object={nodes['P-BB-Cheek_4_1L']} />
      <primitive object={nodes['P-BB-JawLine_1L']} />
      <primitive object={nodes['P-GRP-NostrilL']} />
      <primitive object={nodes['P-BB-Forehead-_TopM']} />
      <primitive object={nodes['GRP-Nose_Bridge2']} />
      <primitive object={nodes['P-BB-Forehead-_Top_1L']} />
      <primitive object={nodes['P-BB-Forehead-_Top_3L']} />
      <primitive object={nodes['P-BB-Forehead-_Top_2L']} />
      <primitive object={nodes['P-BB-Forehead-_1L']} />
      <primitive object={nodes['P-FK-Neck']} />
      <primitive object={nodes['P-BB-Chin_2R']} />
      <primitive object={nodes['P-BB-LaughLine_7R']} />
      <primitive object={nodes['P-BB-JawLine_3R']} />
      <primitive object={nodes['P-BB-Cheek_SneerR']} />
      <primitive object={nodes['P-BB-Cheek_3_2R']} />
      <primitive object={nodes['P-BB-Cheek_2_2R']} />
      <primitive object={nodes['P-BB-LaughLine_2R']} />
      <primitive object={nodes['P-BB-Nostril_2R']} />
      <primitive object={nodes['P-BB-Nostril_1R']} />
      <primitive object={nodes['P-BB-LaughLine_1R']} />
      <primitive object={nodes['P-BB-LaughLine_6R']} />
      <primitive object={nodes['P-BB-LaughLine_4R']} />
      <primitive object={nodes['P-BB-Cheek_2_1R']} />
      <primitive object={nodes['P-BB-Cheek_3_1R']} />
      <primitive object={nodes['P-BB-JawLine_2R']} />
      <primitive object={nodes['P-BB-LaughLine_5R']} />
      <primitive object={nodes['P-BB-Cheek_1_2R']} />
      <primitive object={nodes['P-BB-Cheek_4_2R']} />
      <primitive object={nodes['P-BB-Cheek_1_1R']} />
      <primitive object={nodes['P-GRP-Lip_Top_1R']} />
      <primitive object={nodes['P-GRP-Lip_Bot_1R']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Bot_1R']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Top_1R']} />
      <primitive object={nodes['P-BB-Cheek_4_1R']} />
      <primitive object={nodes['P-BB-JawLine_1R']} />
      <primitive object={nodes['P-GRP-NostrilR']} />
      <primitive object={nodes['P-BB-Forehead-_Top_1R']} />
      <primitive object={nodes['P-BB-Forehead-_Top_3R']} />
      <primitive object={nodes['P-BB-Forehead-_Top_2R']} />
      <primitive object={nodes['P-BB-Forehead-_1R']} />
      <primitive object={nodes['P-GRP-Nose_Bridge']} />
      <primitive object={nodes['CTR-COR-Thumb_2L']} />
      <primitive object={nodes['GRP-STR-Nose_Front']} />
      <primitive object={nodes['GRP-STR-NostrilL']} />
      <primitive object={nodes['GRP-STR-NostrilR']} />
      <primitive object={nodes['P-SK-Cheek_PuffL']} />
      <primitive object={nodes['P-SK-Cheek_PuffR']} />
      <primitive object={nodes['FK-ToeR']} />
      <primitive object={nodes['DEF-COR-Shin_TopR']} />
      <primitive object={nodes['HNG-ThighR']} />
      <primitive object={nodes['HNG-Upperarm_ParentR']} />
      <primitive object={nodes['CTR-COR-Thumb_1R']} />
      <primitive object={nodes['CTR-COR-Thumb_2R']} />
      <primitive object={nodes.Root_EarL} />
      <primitive object={nodes.Root_EarR} />
      <primitive object={nodes['GRAB-HandL']} />
      <primitive object={nodes['N-BB-Forehead-_TopM']} />
      <primitive object={nodes['N-TAN-Forehead_2M']} />
      <primitive object={nodes['N-BB-Eyebrow_TopM']} />
      <primitive object={nodes['N-TAN-Eyebrow_AcrossM']} />
      <primitive object={nodes['N-BB-Eyebrow_BotM']} />
      <primitive object={nodes['N-TAN-Nose_1M']} />
      <primitive object={nodes['N-BB-Nose_1M']} />
      <primitive object={nodes['N-TAN-Nose_2M']} />
      <primitive object={nodes['N-BB-Nose_2M']} />
      <primitive object={nodes['N-TAN-Nose_3M']} />
      <primitive object={nodes['N-BB-Nose_3M']} />
      <primitive object={nodes['N-TAN-Nose_4M']} />
      <primitive object={nodes['N-BB-Nose_4M']} />
      <primitive object={nodes['N-TAN-Nose_5M']} />
      <primitive object={nodes['N-BB-Lip_Top_TopM']} />
      <primitive object={nodes['N-TAN-Lip_Top_AcrossM']} />
      <primitive object={nodes['N-BB-Lip_Top_BotM']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_AcrossM']} />
      <primitive object={nodes['N-BB-LaughLine_3L']} />
      <primitive object={nodes['N-TAN-NoseRing_3L']} />
      <primitive object={nodes['N-BB-LaughLine_2L']} />
      <primitive object={nodes['N-TAN-NoseRing_4L']} />
      <primitive object={nodes['N-BB-LaughLine_1L']} />
      <primitive object={nodes['N-TAN-NoseRing_5L']} />
      <primitive object={nodes['N-TAN-Tail-NoseRing_5L']} />
      <primitive object={nodes['N-TAN-NoseFront_1L']} />
      <primitive object={nodes['N-BB-Nostril_1L']} />
      <primitive object={nodes['N-TAN-NoseFront_2L']} />
      <primitive object={nodes['N-TAN-Tail-NoseFront_2L']} />
      <primitive object={nodes['N-BB-Forehead-_Top_1L']} />
      <primitive object={nodes['N-TAN-Forehead_2_2L']} />
      <primitive object={nodes['N-BB-Eyebrow_Top_1L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Across_1L']} />
      <primitive object={nodes['N-BB-Eyebrow_Bot_1L']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_2L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_2L']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_2L']} />
      <primitive object={nodes['N-BB-Eyelid_Top_2L']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_2L']} />
      <primitive object={nodes['N-BB-Forehead-_1L']} />
      <primitive object={nodes['N-TAN-Forehead_1_2L']} />
      <primitive object={nodes['N-BB-Eyebrow_1L']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_1L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_1L']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_1L']} />
      <primitive object={nodes['N-BB-Eyelid_Top_1L']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_1L']} />
      <primitive object={nodes['N-BB-Forehead-_Top_3L']} />
      <primitive object={nodes['N-TAN-Forehead_4_2L']} />
      <primitive object={nodes['N-BB-Eyebrow_Top_3L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Across_3L']} />
      <primitive object={nodes['N-BB-Eyebrow_Bot_3L']} />
      <primitive object={nodes['N-TAN-FaceRing_1L']} />
      <primitive object={nodes['N-BB-NoseBridge_1L']} />
      <primitive object={nodes['N-TAN-FaceRing_2L']} />
      <primitive object={nodes['N-BB-NoseBridge_2L']} />
      <primitive object={nodes['N-TAN-FaceRing_3L']} />
      <primitive object={nodes['N-BB-Cheek_SneerL']} />
      <primitive object={nodes['N-TAN-FaceRing_4L']} />
      <primitive object={nodes['N-BB-Cheek_2_1L']} />
      <primitive object={nodes['N-TAN-FaceRing_5L']} />
      <primitive object={nodes['N-BB-Cheek_3_1L']} />
      <primitive object={nodes['N-TAN-FaceRing_6L']} />
      <primitive object={nodes['N-BB-Cheek_4_1L']} />
      <primitive object={nodes['N-TAN-FaceRing_7L']} />
      <primitive object={nodes['N-BB-Cheek_5_1L']} />
      <primitive object={nodes['N-TAN-FaceRing_8L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_1L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_2L']} />
      <primitive object={nodes['N-BB-Eyebrow_Top_2L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_3L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_4L']} />
      <primitive object={nodes['N-TAN-Tail-Eyebrow_Upper_4L']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_4L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_4L']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_4L']} />
      <primitive object={nodes['N-BB-Eyelid_Top_4L']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_4L']} />
      <primitive object={nodes['N-BB-Forehead-_Top_2L']} />
      <primitive object={nodes['N-TAN-Forehead_3_2L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Across_2L']} />
      <primitive object={nodes['N-BB-Eyebrow_Bot_2L']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_3L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_3L']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_3L']} />
      <primitive object={nodes['N-BB-Eyelid_Top_3L']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_3L']} />
      <primitive object={nodes['N-BB-TempleL']} />
      <primitive object={nodes['N-TAN-Temple_2L']} />
      <primitive object={nodes['N-BB-JawLine_1L']} />
      <primitive object={nodes['N-TAN-JawLine_1L']} />
      <primitive object={nodes['N-BB-JawLine_2L']} />
      <primitive object={nodes['N-TAN-JawLine_2L']} />
      <primitive object={nodes['N-BB-JawLine_3L']} />
      <primitive object={nodes['N-TAN-JawLine_3L']} />
      <primitive object={nodes['N-BB-JawLine_4L']} />
      <primitive object={nodes['N-TAN-JawLine_4L']} />
      <primitive object={nodes['N-BB-JawLine_5L']} />
      <primitive object={nodes['N-TAN-JawLine_5L']} />
      <primitive object={nodes['N-BB-JawLineM']} />
      <primitive object={nodes['N-TAN-Tail-JawLine_5L']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_5L']} />
      <primitive object={nodes['N-TAN-Cheek_4_0L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_9L']} />
      <primitive object={nodes['N-TAN-Cheek_4_1L']} />
      <primitive object={nodes['N-TAN-Cheek_Jawline_Across_1L']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_Jawline_Across_1L']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_1L']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_2L']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_3L']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_4L']} />
      <primitive object={nodes['N-BB-Eyelid_Top_5L']} />
      <primitive object={nodes['N-TAN-Tail-Eyelid_Top_4L']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_1L']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_1L']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_2L']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_2L']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_3L']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_3L']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_4L']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_4L']} />
      <primitive object={nodes['N-TAN-Tail-Eyelid_Bot_4L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_5L']} />
      <primitive object={nodes['N-TAN-NoseBridge_2_2L']} />
      <primitive object={nodes['N-TAN-NoseBridge_2_3L']} />
      <primitive object={nodes['N-TAN-Tail-NoseBridge_2_3L']} />
      <primitive object={nodes['N-TAN-NoseMidLine_3L']} />
      <primitive object={nodes['N-TAN-NoseMidLine_2L']} />
      <primitive object={nodes['N-TAN-NoseMidLine_1L']} />
      <primitive object={nodes['N-BB-Lip_Top_TopL']} />
      <primitive object={nodes['N-TAN-Lip_Top_AcrossL']} />
      <primitive object={nodes['N-BB-Lip_Top_BotL']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_AcrossL']} />
      <primitive object={nodes['N-TAN-Cheek_2_0L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_7L']} />
      <primitive object={nodes['N-TAN-Cheek_2_1L']} />
      <primitive object={nodes['N-TAN-Cheek_2_2L']} />
      <primitive object={nodes['N-BB-Cheek_2_2L']} />
      <primitive object={nodes['N-TAN-Cheek_2_3L']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_2_3L']} />
      <primitive object={nodes['N-TAN-NoseCrease_0L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_6L']} />
      <primitive object={nodes['N-TAN-NoseCrease_1L']} />
      <primitive object={nodes['N-TAN-NoseCrease_2L']} />
      <primitive object={nodes['N-TAN-Tail-NoseCrease_2L']} />
      <primitive object={nodes['N-TAN-Cheek_3_0L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_8L']} />
      <primitive object={nodes['N-TAN-Cheek_3_1L']} />
      <primitive object={nodes['N-TAN-Cheek_3_2L']} />
      <primitive object={nodes['N-BB-Cheek_3_2L']} />
      <primitive object={nodes['N-TAN-Cheek_Jawline_Across_3L']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_Jawline_Across_3L']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_10L']} />
      <primitive object={nodes['N-TAN-Cheek_5_1L']} />
      <primitive object={nodes['N-TAN-Cheek_5_2L']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_5_2L']} />
      <primitive object={nodes['N-TAN-Cheek_4_2L']} />
      <primitive object={nodes['N-BB-Cheek_4_2L']} />
      <primitive object={nodes['N-TAN-Cheek_4_3L']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_4_3L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_1L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_2L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_3L']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_4L']} />
      <primitive object={nodes['N-TAN-Tail-Eyebrow_Lower_4L']} />
      <primitive object={nodes['N-BB-Lip_Bot_BotL']} />
      <primitive object={nodes['N-TAN-Lip_Bot_AcrossL']} />
      <primitive object={nodes['N-BB-Lip_Bot_TopL']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_AcrossL']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_4L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_5L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_6L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_7L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_8L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_9L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_10L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_1L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_2L']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_3L']} />
      <primitive object={nodes['N-TAN-NoseBridge_1_2L']} />
      <primitive object={nodes['N-TAN-NoseBridge_1_1L']} />
      <primitive object={nodes['N-TAN-Tail-NoseBridge_1_1L']} />
      <primitive object={nodes['N-BB-Chin_2L']} />
      <primitive object={nodes['N-TAN-Cheek_1_4L']} />
      <primitive object={nodes['N-BB-ChinM']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_1_4L']} />
      <primitive object={nodes['N-BB-LaughLineM']} />
      <primitive object={nodes['N-TAN-LaughLine_5L']} />
      <primitive object={nodes['N-BB-LaughLine_7L']} />
      <primitive object={nodes['N-TAN-LaughLine_4L']} />
      <primitive object={nodes['N-BB-LaughLine_6L']} />
      <primitive object={nodes['N-TAN-LaughLine_3L']} />
      <primitive object={nodes['N-BB-LaughLine_5L']} />
      <primitive object={nodes['N-TAN-LaughLine_2L']} />
      <primitive object={nodes['N-BB-LaughLine_4L']} />
      <primitive object={nodes['N-TAN-LaughLine_1L']} />
      <primitive object={nodes['N-TAN-Tail-LaughLine_1L']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Bot_2L']} />
      <primitive object={nodes['N-BB-Lip_Bot_CornerL']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_Bot_2L']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Top_2L']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_Top_2L']} />
      <primitive object={nodes['N-TAN-Cheek_1_1L']} />
      <primitive object={nodes['N-BB-Cheek_1_1L']} />
      <primitive object={nodes['N-TAN-Cheek_1_2L']} />
      <primitive object={nodes['N-BB-Cheek_1_2L']} />
      <primitive object={nodes['N-TAN-Cheek_1_3L']} />
      <primitive object={nodes['N-BB-Lip_Top_CornerL']} />
      <primitive object={nodes['N-TAN-Lip_Top_Top_2L']} />
      <primitive object={nodes['N-TAN-Lip_Top_Top_1L']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_Top_1L']} />
      <primitive object={nodes['N-TAN-Lip_Top_Bot_2L']} />
      <primitive object={nodes['N-TAN-Lip_Top_Bot_1L']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_Bot_1L']} />
      <primitive object={nodes['N-TAN-LaughLine_Lip_Across_1L']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_1_1L']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_1_2L']} />
      <primitive object={nodes['N-TAN-Tail-LaughLine_Cheek_Across_1_2L']} />
      <primitive object={nodes['N-TAN-LaughLine_Lip_Across_2L']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_2_1L']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_2_2L']} />
      <primitive object={nodes['N-TAN-Cheek_Cheek_Across_1L']} />
      <primitive object={nodes['N-TAN-Cheek_Cheek_Across_2L']} />
      <primitive object={nodes['N-TAN-Cheek_Jawline_AcrossL']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_Jawline_AcrossL']} />
      <primitive object={nodes['N-BB-Lip_AboveM']} />
      <primitive object={nodes['N-TAN-NoseRing_1L']} />
      <primitive object={nodes['N-TAN-Nose_Lip_AcrossM']} />
      <primitive object={nodes['N-BB-Nostril_2L']} />
      <primitive object={nodes['N-TAN-NoseRing_2L']} />
      <primitive object={nodes['N-TAN-Tail-NoseMidLine_1L']} />
      <primitive object={nodes['N-TAN-Nose_Lip_AcrossL']} />
      <primitive object={nodes.ROOT} />
      <primitive object={nodes['TGT-Eyes']} />
      <primitive object={nodes['N-BB-LaughLine_3R']} />
      <primitive object={nodes['N-TAN-NoseRing_3R']} />
      <primitive object={nodes['N-BB-LaughLine_2R']} />
      <primitive object={nodes['N-TAN-NoseRing_4R']} />
      <primitive object={nodes['N-BB-LaughLine_1R']} />
      <primitive object={nodes['N-TAN-NoseRing_5R']} />
      <primitive object={nodes['N-TAN-Tail-NoseRing_5R']} />
      <primitive object={nodes['N-TAN-NoseFront_1R']} />
      <primitive object={nodes['N-BB-Nostril_1R']} />
      <primitive object={nodes['N-TAN-NoseFront_2R']} />
      <primitive object={nodes['N-TAN-Tail-NoseFront_2R']} />
      <primitive object={nodes['N-BB-Forehead-_Top_1R']} />
      <primitive object={nodes['N-TAN-Forehead_2_2R']} />
      <primitive object={nodes['N-BB-Eyebrow_Top_1R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Across_1R']} />
      <primitive object={nodes['N-BB-Eyebrow_Bot_1R']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_2R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_2R']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_2R']} />
      <primitive object={nodes['N-BB-Eyelid_Top_2R']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_2R']} />
      <primitive object={nodes['N-BB-Forehead-_1R']} />
      <primitive object={nodes['N-TAN-Forehead_1_2R']} />
      <primitive object={nodes['N-BB-Eyebrow_1R']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_1R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_1R']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_1R']} />
      <primitive object={nodes['N-BB-Eyelid_Top_1R']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_1R']} />
      <primitive object={nodes['N-BB-Forehead-_Top_3R']} />
      <primitive object={nodes['N-TAN-Forehead_4_2R']} />
      <primitive object={nodes['N-BB-Eyebrow_Top_3R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Across_3R']} />
      <primitive object={nodes['N-BB-Eyebrow_Bot_3R']} />
      <primitive object={nodes['N-TAN-FaceRing_1R']} />
      <primitive object={nodes['N-BB-NoseBridge_1R']} />
      <primitive object={nodes['N-TAN-FaceRing_2R']} />
      <primitive object={nodes['N-BB-NoseBridge_2R']} />
      <primitive object={nodes['N-TAN-FaceRing_3R']} />
      <primitive object={nodes['N-BB-Cheek_SneerR']} />
      <primitive object={nodes['N-TAN-FaceRing_4R']} />
      <primitive object={nodes['N-BB-Cheek_2_1R']} />
      <primitive object={nodes['N-TAN-FaceRing_5R']} />
      <primitive object={nodes['N-BB-Cheek_3_1R']} />
      <primitive object={nodes['N-TAN-FaceRing_6R']} />
      <primitive object={nodes['N-BB-Cheek_4_1R']} />
      <primitive object={nodes['N-TAN-FaceRing_7R']} />
      <primitive object={nodes['N-BB-Cheek_5_1R']} />
      <primitive object={nodes['N-TAN-FaceRing_8R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_1R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_2R']} />
      <primitive object={nodes['N-BB-Eyebrow_Top_2R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_3R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Upper_4R']} />
      <primitive object={nodes['N-TAN-Tail-Eyebrow_Upper_4R']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_4R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_4R']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_4R']} />
      <primitive object={nodes['N-BB-Eyelid_Top_4R']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_4R']} />
      <primitive object={nodes['N-BB-Forehead-_Top_2R']} />
      <primitive object={nodes['N-TAN-Forehead_3_2R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Across_2R']} />
      <primitive object={nodes['N-BB-Eyebrow_Bot_2R']} />
      <primitive object={nodes['N-TAN-Brow_Crease_Across_3R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_3R']} />
      <primitive object={nodes['N-TAN-Crease_Lid_Across_3R']} />
      <primitive object={nodes['N-BB-Eyelid_Top_3R']} />
      <primitive object={nodes['N-TAN-Tail-Crease_Lid_Across_3R']} />
      <primitive object={nodes['N-BB-TempleR']} />
      <primitive object={nodes['N-TAN-Temple_2R']} />
      <primitive object={nodes['N-BB-JawLine_1R']} />
      <primitive object={nodes['N-TAN-JawLine_1R']} />
      <primitive object={nodes['N-BB-JawLine_2R']} />
      <primitive object={nodes['N-TAN-JawLine_2R']} />
      <primitive object={nodes['N-BB-JawLine_3R']} />
      <primitive object={nodes['N-TAN-JawLine_3R']} />
      <primitive object={nodes['N-BB-JawLine_4R']} />
      <primitive object={nodes['N-TAN-JawLine_4R']} />
      <primitive object={nodes['N-BB-JawLine_5R']} />
      <primitive object={nodes['N-TAN-JawLine_5R']} />
      <primitive object={nodes['N-TAN-Tail-JawLine_5R']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_5R']} />
      <primitive object={nodes['N-TAN-Cheek_4_0R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_9R']} />
      <primitive object={nodes['N-TAN-Cheek_4_1R']} />
      <primitive object={nodes['N-TAN-Cheek_Jawline_Across_1R']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_Jawline_Across_1R']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_1R']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_2R']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_3R']} />
      <primitive object={nodes['N-TAN-Eyelid_Top_4R']} />
      <primitive object={nodes['N-BB-Eyelid_Top_5R']} />
      <primitive object={nodes['N-TAN-Tail-Eyelid_Top_4R']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_1R']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_1R']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_2R']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_2R']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_3R']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_3R']} />
      <primitive object={nodes['N-BB-Eyelid_Bot_4R']} />
      <primitive object={nodes['N-TAN-Eyelid_Bot_4R']} />
      <primitive object={nodes['N-TAN-Tail-Eyelid_Bot_4R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_5R']} />
      <primitive object={nodes['N-TAN-NoseBridge_2_2R']} />
      <primitive object={nodes['N-TAN-NoseBridge_2_3R']} />
      <primitive object={nodes['N-TAN-Tail-NoseBridge_2_3R']} />
      <primitive object={nodes['N-TAN-NoseMidLine_3R']} />
      <primitive object={nodes['N-TAN-NoseMidLine_2R']} />
      <primitive object={nodes['N-TAN-NoseMidLine_1R']} />
      <primitive object={nodes['N-BB-Lip_Top_TopR']} />
      <primitive object={nodes['N-TAN-Lip_Top_AcrossR']} />
      <primitive object={nodes['N-BB-Lip_Top_BotR']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_AcrossR']} />
      <primitive object={nodes['N-TAN-Cheek_2_0R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_7R']} />
      <primitive object={nodes['N-TAN-Cheek_2_1R']} />
      <primitive object={nodes['N-TAN-Cheek_2_2R']} />
      <primitive object={nodes['N-BB-Cheek_2_2R']} />
      <primitive object={nodes['N-TAN-Cheek_2_3R']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_2_3R']} />
      <primitive object={nodes['N-TAN-NoseCrease_0R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_6R']} />
      <primitive object={nodes['N-TAN-NoseCrease_1R']} />
      <primitive object={nodes['N-TAN-NoseCrease_2R']} />
      <primitive object={nodes['N-TAN-Tail-NoseCrease_2R']} />
      <primitive object={nodes['N-TAN-Cheek_3_0R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_8R']} />
      <primitive object={nodes['N-TAN-Cheek_3_1R']} />
      <primitive object={nodes['N-TAN-Cheek_3_2R']} />
      <primitive object={nodes['N-BB-Cheek_3_2R']} />
      <primitive object={nodes['N-TAN-Cheek_Jawline_Across_3R']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_Jawline_Across_3R']} />
      <primitive object={nodes['N-BB-EyeLid_Crease_10R']} />
      <primitive object={nodes['N-TAN-Cheek_5_1R']} />
      <primitive object={nodes['N-TAN-Cheek_5_2R']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_5_2R']} />
      <primitive object={nodes['N-TAN-Cheek_4_2R']} />
      <primitive object={nodes['N-BB-Cheek_4_2R']} />
      <primitive object={nodes['N-TAN-Cheek_4_3R']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_4_3R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_1R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_2R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_3R']} />
      <primitive object={nodes['N-TAN-Eyebrow_Lower_4R']} />
      <primitive object={nodes['N-TAN-Tail-Eyebrow_Lower_4R']} />
      <primitive object={nodes['N-BB-Lip_Bot_BotR']} />
      <primitive object={nodes['N-TAN-Lip_Bot_AcrossR']} />
      <primitive object={nodes['N-BB-Lip_Bot_TopR']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_AcrossR']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_4R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_5R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_6R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_7R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_8R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_9R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_10R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_1R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_2R']} />
      <primitive object={nodes['N-TAN-EyeLid_Crease_3R']} />
      <primitive object={nodes['N-TAN-NoseBridge_1_2R']} />
      <primitive object={nodes['N-TAN-NoseBridge_1_1R']} />
      <primitive object={nodes['N-TAN-Tail-NoseBridge_1_1R']} />
      <primitive object={nodes['N-BB-Chin_2R']} />
      <primitive object={nodes['N-TAN-Cheek_1_4R']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_1_4R']} />
      <primitive object={nodes['N-TAN-LaughLine_5R']} />
      <primitive object={nodes['N-BB-LaughLine_7R']} />
      <primitive object={nodes['N-TAN-LaughLine_4R']} />
      <primitive object={nodes['N-BB-LaughLine_6R']} />
      <primitive object={nodes['N-TAN-LaughLine_3R']} />
      <primitive object={nodes['N-BB-LaughLine_5R']} />
      <primitive object={nodes['N-TAN-LaughLine_2R']} />
      <primitive object={nodes['N-BB-LaughLine_4R']} />
      <primitive object={nodes['N-TAN-LaughLine_1R']} />
      <primitive object={nodes['N-TAN-Tail-LaughLine_1R']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Bot_2R']} />
      <primitive object={nodes['N-BB-Lip_Bot_CornerR']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_Bot_2R']} />
      <primitive object={nodes['N-TAN-Lip_Bot_Top_2R']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Bot_Top_2R']} />
      <primitive object={nodes['N-TAN-Cheek_1_1R']} />
      <primitive object={nodes['N-BB-Cheek_1_1R']} />
      <primitive object={nodes['N-TAN-Cheek_1_2R']} />
      <primitive object={nodes['N-BB-Cheek_1_2R']} />
      <primitive object={nodes['N-TAN-Cheek_1_3R']} />
      <primitive object={nodes['N-BB-Lip_Top_CornerR']} />
      <primitive object={nodes['N-TAN-Lip_Top_Top_2R']} />
      <primitive object={nodes['N-TAN-Lip_Top_Top_1R']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_Top_1R']} />
      <primitive object={nodes['N-TAN-Lip_Top_Bot_2R']} />
      <primitive object={nodes['N-TAN-Lip_Top_Bot_1R']} />
      <primitive object={nodes['N-TAN-Tail-Lip_Top_Bot_1R']} />
      <primitive object={nodes['N-TAN-LaughLine_Lip_Across_1R']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_1_1R']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_1_2R']} />
      <primitive object={nodes['N-TAN-Tail-LaughLine_Cheek_Across_1_2R']} />
      <primitive object={nodes['N-TAN-LaughLine_Lip_Across_2R']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_2_1R']} />
      <primitive object={nodes['N-TAN-LaughLine_Cheek_Across_2_2R']} />
      <primitive object={nodes['N-TAN-Cheek_Cheek_Across_1R']} />
      <primitive object={nodes['N-TAN-Cheek_Cheek_Across_2R']} />
      <primitive object={nodes['N-TAN-Cheek_Jawline_AcrossR']} />
      <primitive object={nodes['N-TAN-Tail-Cheek_Jawline_AcrossR']} />
      <primitive object={nodes['N-TAN-NoseRing_1R']} />
      <primitive object={nodes['N-BB-Nostril_2R']} />
      <primitive object={nodes['N-TAN-NoseRing_2R']} />
      <primitive object={nodes['N-TAN-Tail-NoseMidLine_1R']} />
      <primitive object={nodes['N-TAN-Nose_Lip_AcrossR']} />
      <primitive object={nodes['GRAB-HandR']} />
      <primitive object={nodes['IK-P-Pole-ForearmL']} />
      <primitive object={nodes['IK-P-Pole-ShinL']} />
      <primitive object={nodes['IK-P-Hand_ParentL']} />
      <primitive object={nodes['MSTR-P-Foot_ParentL']} />
      <primitive object={nodes['IK-P-Pole-ForearmR']} />
      <primitive object={nodes['IK-P-Pole-ShinR']} />
      <primitive object={nodes['IK-P-Hand_ParentR']} />
      <primitive object={nodes['MSTR-P-Foot_ParentR']} />
     
     
       
      <skinnedMesh
        geometry={nodes['GEO-rain_gums_upper_Data'].geometry}
        material={nodes['GEO-rain_gums_upper_Data'].material}
        skeleton={nodes['GEO-rain_gums_upper_Data'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['GEO-rain_gums_upper_Data_1'].geometry}
        material={nodes['GEO-rain_gums_upper_Data_1'].material}
        skeleton={nodes['GEO-rain_gums_upper_Data_1'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['GEO-rain_hair_ponytail'].geometry}
        material={nodes['GEO-rain_hair_ponytail'].material}
        skeleton={nodes['GEO-rain_hair_ponytail'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['GEO-rain_hair_strand'].geometry}
        material={nodes['GEO-rain_hair_strand'].material}
        skeleton={nodes['GEO-rain_hair_strand'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['GEO-rain_hairband'].geometry}
        material={materials['MAT-rain.hairband']}
        skeleton={nodes['GEO-rain_hairband'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['GEO-rain_scarf'].geometry}
        material={materials['MAT-rain.scarf']}
        skeleton={nodes['GEO-rain_scarf'].skeleton}
      />
      <skinnedMesh
        name="GEO-rain_head"
        geometry={nodes['GEO-rain_head'].geometry}
        material={nodes['GEO-rain_head'].material}
        skeleton={nodes['GEO-rain_head'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_head'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_head'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_body"
        geometry={nodes['GEO-rain_body'].geometry}
        material={nodes['GEO-rain_body'].material}
        skeleton={nodes['GEO-rain_body'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_body'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_body'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_jeans"
        geometry={nodes['GEO-rain_jeans'].geometry}
        material={materials['MAT-rain.jeans']}
        skeleton={nodes['GEO-rain_jeans'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_jeans'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_jeans'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_shoes_Data"
        geometry={nodes['GEO-rain_shoes_Data'].geometry}
        material={materials['MAT-rain.shoes']}
        skeleton={nodes['GEO-rain_shoes_Data'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_shoes_Data'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_shoes_Data'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_shoes_Data_1"
        geometry={nodes['GEO-rain_shoes_Data_1'].geometry}
        material={materials['MAT-rain.metal']}
        skeleton={nodes['GEO-rain_shoes_Data_1'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_shoes_Data_1'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_shoes_Data_1'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_shoes_Data_2"
        geometry={nodes['GEO-rain_shoes_Data_2'].geometry}
        material={materials['MAT-rain.socks']}
        skeleton={nodes['GEO-rain_shoes_Data_2'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_shoes_Data_2'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_shoes_Data_2'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_shoes_Data_3"
        geometry={nodes['GEO-rain_shoes_Data_3'].geometry}
        material={materials['MAT-rain.laces']}
        skeleton={nodes['GEO-rain_shoes_Data_3'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_shoes_Data_3'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_shoes_Data_3'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_top"
        geometry={nodes['GEO-rain_top'].geometry}
        material={materials['MAT-rain.top']}
        skeleton={nodes['GEO-rain_top'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_top'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_top'].morphTargetInfluences}
        onClick={() => setIndex((index + 1) % names.length)}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
      />
      <skinnedMesh
        name="GEO-rain_body_nomask_Data"
        geometry={nodes['GEO-rain_body_nomask_Data'].geometry}
        material={materials['MAT-rain.hands']}
        skeleton={nodes['GEO-rain_body_nomask_Data'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_body_nomask_Data'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_body_nomask_Data'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_body_nomask_Data_1"
        geometry={nodes['GEO-rain_body_nomask_Data_1'].geometry}
        material={materials['MAT-rain.body.001']}
        skeleton={nodes['GEO-rain_body_nomask_Data_1'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_body_nomask_Data_1'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_body_nomask_Data_1'].morphTargetInfluences}
      />
      {/* take the black out the eye */}
      {/* <skinnedMesh
        name="GEO-rain_eye_cornea"
        geometry={nodes['GEO-rain_eye_cornea'].geometry}
        material={materials['MAT-rain.cornea']}
        skeleton={nodes['GEO-rain_eye_cornea'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_eye_cornea'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_eye_cornea'].morphTargetInfluences}
      /> */}
   
     
      
      <skinnedMesh
        name="GEO-rain_eyes"
        geometry={nodes['GEO-rain_eyes'].geometry}
        material={materials['MAT-rain.eyes']}
        skeleton={nodes['GEO-rain_eyes'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_eyes'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_eyes'].morphTargetInfluences}
      >
       <skinnedMesh
        geometry={nodes['GEO-rain_eye_dots'].geometry}
        material={materials['MAT-rain.eyedot']}
        skeleton={nodes['GEO-rain_eye_dots'].skeleton}
      />
       <skinnedMesh
        name="GEO-rain_eyelashes"
        geometry={nodes['GEO-rain_eyelashes'].geometry}
        material={materials['MAT-rain.eyelashes']}
        skeleton={nodes['GEO-rain_eyelashes'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_eyelashes'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_eyelashes'].morphTargetInfluences}
      />
       <skinnedMesh
        name="GEO-rain_eyelashes"
        geometry={nodes['GEO-rain_eyelashes'].geometry}
        material={materials['MAT-rain.eyelashes']}
        skeleton={nodes['GEO-rain_eyelashes'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_eyelashes'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_eyelashes'].morphTargetInfluences}
      />
       <skinnedMesh
        geometry={nodes['GEO-rain_eyebrows'].geometry}
        material={materials['MAT-rain.eyebrows']}
        skeleton={nodes['GEO-rain_eyebrows'].skeleton}
     
      />
     </skinnedMesh>
     
     
      <skinnedMesh
        name="GEO-rain_gums_lower_Data"
        geometry={nodes['GEO-rain_gums_lower_Data'].geometry}
        material={nodes['GEO-rain_gums_lower_Data'].material}
        skeleton={nodes['GEO-rain_gums_lower_Data'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_gums_lower_Data'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_gums_lower_Data'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_gums_lower_Data_1"
        geometry={nodes['GEO-rain_gums_lower_Data_1'].geometry}
        material={nodes['GEO-rain_gums_lower_Data_1'].material}
        skeleton={nodes['GEO-rain_gums_lower_Data_1'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_gums_lower_Data_1'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_gums_lower_Data_1'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_hair_main"
        geometry={nodes['GEO-rain_hair_main'].geometry}
        material={nodes['GEO-rain_hair_main'].material}
        skeleton={nodes['GEO-rain_hair_main'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_hair_main'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_hair_main'].morphTargetInfluences}
      />
      <skinnedMesh
        name="GEO-rain_tongue"
        geometry={nodes['GEO-rain_tongue'].geometry}
        material={materials['MAT-rain.tongue']}
        skeleton={nodes['GEO-rain_tongue'].skeleton}
        morphTargetDictionary={nodes['GEO-rain_tongue'].morphTargetDictionary}
        morphTargetInfluences={nodes['GEO-rain_tongue'].morphTargetInfluences}
      />
    </group>
  )
}

useGLTF.preload('/rain_rig.glb')
