/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/timmy.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    nodes.mixamorig6Hips.position.addScalar(-5)
  
 
   
    actions["standing.001"].play()
    //actions.hello.time=5
    actions.hello.startAt(10)
   console.log(nodes)
   })
  console.log(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
        <primitive object={nodes.mixamorig6Hips} />
        <skinnedMesh geometry={nodes.Ch09.geometry} material={materials.Ch09_body} skeleton={nodes.Ch09.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/timmy.glb')
